### PR TITLE
Upgrade to proc-macro-error 1.0.0

### PR DESCRIPTION
**Pull request by cuviper**
No code changes needed.

### CODE REVIEW

**Comment by hannesg** [comment]
Hi @cuviper,

There is already `1.0.2`. Maybe just depend on `1.0`?

**Comment by cuviper** [comment]
I can change it if you like, but cargo treats these as caret requirements, so "1", "1.0", and "1.0.0" all effectively mean `>= 1.0.0, < 2.0.0`.

See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by davidpdrsn** [comment]
I think we should set it to “1”. It might technically the same as others but I think “1” is the clearest.

Thanks for the pr by the way 😊 I really should setup dependabot on all my repos.

**Comment by cuviper** [comment]
Alright, now it's just "1".

**Pull request merged**
